name = "AqDados"
uuid = "20b6619c-8715-4d08-8fff-0085844e4ef2"
authors = ["Paulo Jabardo <pjabardo@ipt.br>"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
